name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - "v*"

jobs:
  build:
    uses: ministruth/.github/.github/workflows/build.yml@main
